# Aurelia Dark — Kitty colors
# Included by ~/.config/kitty/kitty.conf

foreground            #E1E4EA
background            #181B25
selection_foreground  #181B25
selection_background  #F05629

cursor            #F05629
cursor_text_color #181B25

active_border_color   #F05629
inactive_border_color #2B303B
active_tab_background #F05629
active_tab_foreground #181B25

color0  #1D2130
color1  #E8778A
color2  #72C9A0
color3  #F5936A
color4  #7EB8FA
color5  #BF90F5
color6  #5EC9D6
color7  #B9C2D8
color8  #2D3347
color9  #F08C9D
color10 #90DDB8
color11 #FAA98A
color12 #9DCAFD
color13 #D1AEFA
color14 #7ADAE5
color15 #E1E4EA
